### ISSUE TITLE
Split dependencies out of main project.

### ISSUE THREAD

**Issue by bsermons** [turner-industries/Turner.Infrastructure.Mediator#8]
EntityFramework and HangFire should be split out into their own subprojects since they aren't relevant to all projects using this library.  The hard TransactionHandler decorator specifically seems to be causing some unneeded grief in mobile projects.

**Comment by epicbrownie** [comment]
Oh wow, this was actually on my list of things to do for a completely different reason, so I really appreciate you taking this issue!
